[package]
name = "mailstrom"
version = "0.3.0"
description = "Email sender"
authors = ["Mike Dilger <mike@optcomp.nz>"]
readme = "README.md"
repository = "https://github.com/mikedilger/mailstrom"
documentation = "https://mikedilger.github.io/mailstrom"
license = "MIT OR Apache-2.0"
keywords = [ "email" ]

[dev-dependencies]
env_logger = "0.3"

[dependencies]
uuid = { version = "0.3", features = [ "v4" ] }
email-format = "0.3"
resolv = ">=0.1.3"
lettre = { git = "https://github.com/lettre/lettre", rev = "90b00ae4ffc8828041160dc4cb579d53f4173c8e" }
log = "0.3"
serde = "0.8"
serde_derive = "0.8"
